// =============================================================================
// api-service/src/main.rs — API Service Entry Point
// =============================================================================
//
// This is the standalone API service binary. It starts a gRPC server that
// accepts CreateTask and GetTaskStatus requests.
//
// ARCHITECTURE:
//   This file is the "composition root" — where we wire together all the
//   layers of Clean Architecture:
//
//   1. Create infrastructure (SQLite pool, event bus)
//   2. Create application handlers (injecting infrastructure)
//   3. Create gRPC service (injecting handlers)
//   4. Start the gRPC server
//
//   This is the ONLY place where concrete types are assembled.
//   The rest of the code works with traits and abstractions.
//
// WHY IS THIS FILE SO SHORT?
//   Because the architecture is clean. Each concern is in its own file:
//   - Domain logic: shared/src/domain.rs
//   - Use cases: api-service/src/application/
//   - Database: api-service/src/infrastructure/sqlite_repo.rs
//   - Events: shared/src/events.rs
//   - gRPC: shared/src/proto/ (generated) + this file (wiring)
//
//   This file only does wiring. If you need to understand the system,
//   you read the individual modules, not this file.
// =============================================================================

// Declare the application and infrastructure modules.
// These are private to this crate — external code can't access them.
mod application;
mod infrastructure;

use application::create_task::CreateTaskHandler;
use application::get_task_status::GetTaskStatusHandler;
use infrastructure::sqlite_repo::SqliteTaskRepository;
use shared::events::InMemoryEventBus;
use shared::proto::task_service_server::{TaskService, TaskServiceServer};
use shared::proto::{
    CreateTaskRequest, CreateTaskResponse, GetTaskStatusRequest, GetTaskStatusResponse,
};
use sqlx::SqlitePool;
use std::sync::Arc;
use tonic::{Request, Response, Status};

// =============================================================================
// gRPC Service Implementation
// =============================================================================
//
// This struct implements the TaskService trait generated by tonic from our
// .proto file. It's the "adapter" between the gRPC framework and our
// application layer.
//
// WHY IS THIS IN main.rs AND NOT A SEPARATE FILE?
//   For this small project, keeping it here is fine. In a larger project,
//   you'd put it in infrastructure/grpc.rs or similar.
pub struct TaskServiceImpl {
    create_handler: CreateTaskHandler<Arc<SqliteTaskRepository>, Arc<InMemoryEventBus>>,
    get_handler: GetTaskStatusHandler<Arc<SqliteTaskRepository>>,
}

// #[tonic::async_trait] is needed because the TaskService trait has async methods.
// This macro transforms the trait to work with async/await (which wasn't
// supported in traits before Rust 1.75).
#[tonic::async_trait]
impl TaskService for TaskServiceImpl {
    /// Handle CreateTask gRPC request.
    ///
    /// Flow:
    ///   1. Extract description from the gRPC request
    ///   2. Validate (description must not be empty)
    ///   3. Delegate to the use case handler
    ///   4. Return the task ID
    async fn create_task(
        &self,
        request: Request<CreateTaskRequest>,
    ) -> Result<Response<CreateTaskResponse>, Status> {
        let description = request.into_inner().description;

        // Input validation at the boundary
        if description.trim().is_empty() {
            return Err(Status::invalid_argument("Description cannot be empty"));
        }

        // Delegate to the application layer (use case)
        let task = self.create_handler.handle(description);

        // Convert domain entity to protobuf response
        Ok(Response::new(CreateTaskResponse { task_id: task.id }))
    }

    /// Handle GetTaskStatus gRPC request.
    ///
    /// Flow:
    ///   1. Extract task_id from the gRPC request
    ///   2. Delegate to the use case handler
    ///   3. Return task status or 404
    async fn get_task_status(
        &self,
        request: Request<GetTaskStatusRequest>,
    ) -> Result<Response<GetTaskStatusResponse>, Status> {
        let task_id = request.into_inner().task_id;

        match self.get_handler.handle(&task_id) {
            Some(task) => Ok(Response::new(GetTaskStatusResponse {
                task_id: task.id,
                status: task.status.as_str().to_string(),
                description: task.description,
            })),
            // gRPC uses Status::not_found for 404-equivalent errors
            None => Err(Status::not_found(format!("Task {} not found", task_id))),
        }
    }
}

// =============================================================================
// Main — Composition Root
// =============================================================================
//
// #[tokio::main] is a macro that transforms the async main function into a
// synchronous one that sets up the tokio runtime and runs the async code.
// It's equivalent to:
//
//   fn main() {
//       let rt = tokio::runtime::Runtime::new().unwrap();
//       rt.block_on(async { ... });
//   }
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Initialize structured logging
    // tracing_subscriber configures where tracing output goes (stdout by default)
    // with_env_filter allows filtering by crate and level (e.g., "api_service=info")
    tracing_subscriber::fmt()
        .with_env_filter("api_service=info,shared=info")
        .init();

    // -----------------------------------------------------------------------
    // Infrastructure Setup
    // -----------------------------------------------------------------------

    // Connect to SQLite. The ?mode=rwc flag means "read-write, create if not exists"
    let db_url = "sqlite:./nextlink.db?mode=rwc";
    let pool = SqlitePool::connect(db_url).await?;
    let repo = Arc::new(SqliteTaskRepository::new(pool.clone()));
    repo.init().await?;

    // Create the in-memory event bus with capacity for 100 buffered events
    let event_bus = Arc::new(InMemoryEventBus::new(100));

    // -----------------------------------------------------------------------
    // Application Layer Setup (Dependency Injection)
    // -----------------------------------------------------------------------

    // Create use case handlers, injecting their dependencies via constructor
    let create_handler = CreateTaskHandler::new(repo.clone(), event_bus.clone());
    let get_handler = GetTaskStatusHandler::new(repo.clone());

    // -----------------------------------------------------------------------
    // gRPC Server Setup
    // -----------------------------------------------------------------------

    // Create the gRPC service with its handlers
    let task_service = TaskServiceImpl {
        create_handler,
        get_handler,
    };

    // Listen on IPv6 localhost (::1) port 50051
    // [::1] is the IPv6 loopback address (equivalent to 127.0.0.1 for IPv4)
    let addr = "[::1]:50051".parse()?;
    tracing::info!("API service listening on {}", addr);

    // Start the gRPC server
    // tonic::transport::Server::builder() creates a new HTTP/2 server
    // .add_service() registers our TaskService implementation
    // .serve() starts listening and handling requests
    tonic::transport::Server::builder()
        .add_service(TaskServiceServer::new(task_service))
        .serve(addr)
        .await?;

    Ok(())
}
