// =============================================================================
// account_service.rs — Command Handlers (Application Layer)
// =============================================================================
//
// WHAT IS THE APPLICATION LAYER?
//   The Application layer sits between the Domain layer (pure types) and the
//   Infrastructure layer (event store, projections). It contains "use cases"
//   — specific business operations that orchestrate domain objects.
//
// COMMAND HANDLER PATTERN:
//   Each command handler:
//   1. Receives a command (intent)
//   2. Loads the current aggregate state from the event store
//   3. Validates the command against business rules
//   4. Produces one or more events
//   5. Appends events to the event store
//   6. Updates projections
//
// WHY SEPARATE FROM DOMAIN?
//   Domain types (Account, AccountEvent) are pure data with no I/O.
//   The service layer handles I/O (database, projections) and orchestration.
//   This separation makes domain logic testable without infrastructure.
// =============================================================================

use crate::domain::{Account, AccountCommand, AccountError, AccountEvent};
use crate::event_store::EventStore;
use crate::projection::ProjectionStore;

/// The account service — handles all account-related commands.
///
/// This is the main entry point for business operations. It coordinates
/// between the event store (write side) and projections (read side).
pub struct AccountService {
    event_store: EventStore,
    projection_store: ProjectionStore,
}

impl AccountService {
    /// Create a new account service.
    pub fn new(event_store: EventStore, projection_store: ProjectionStore) -> Self {
        Self {
            event_store,
            projection_store,
        }
    }

    /// Handle an account command.
    ///
    /// This is the main dispatch method. It routes each command to its
    /// specific handler and returns the resulting events.
    ///
    /// FLOW:
    ///   1. Match on command type
    ///   2. Load aggregate state (if needed)
    ///   3. Validate business rules
    ///   4. Produce events
    ///   5. Append events to store
    ///   6. Update projections
    ///   7. Return events
    pub async fn handle_command(
        &self,
        command: AccountCommand,
    ) -> Result<Vec<AccountEvent>, AccountError> {
        match command {
            AccountCommand::OpenAccount {
                owner,
                initial_balance,
            } => self.handle_open_account(owner, initial_balance).await,

            AccountCommand::Deposit {
                account_id,
                amount,
            } => self.handle_deposit(account_id, amount).await,

            AccountCommand::Withdraw {
                account_id,
                amount,
            } => self.handle_withdraw(account_id, amount).await,
        }
    }

    /// Handle the OpenAccount command.
    ///
    /// BUSINESS RULES:
    ///   - Initial balance must be >= 0 (no negative accounts)
    ///   - Account ID is generated by the system (not provided by client)
    ///
    /// PRODUCES: AccountOpened event
    async fn handle_open_account(
        &self,
        owner: String,
        initial_balance: i64,
    ) -> Result<Vec<AccountEvent>, AccountError> {
        // Validate: initial balance must be non-negative
        if initial_balance < 0 {
            return Err(AccountError::InvalidAmount(initial_balance));
        }

        // Generate a new account ID
        let account_id = uuid::Uuid::new_v4().to_string();
        let opened_at = chrono::Utc::now().to_rfc3339();

        // Create the event
        let event = AccountEvent::AccountOpened {
            account_id: account_id.clone(),
            owner,
            initial_balance,
            opened_at,
        };

        // Append to event store (expected_version = 0 for new stream)
        let stored_events = self
            .event_store
            .append_events(&account_id, 0, &[event.clone()])
            .await?;

        // Update projections
        self.projection_store
            .handle_events(&stored_events)
            .await?;

        tracing::info!(
            account_id = %account_id,
            initial_balance = initial_balance,
            "Account opened"
        );

        Ok(vec![event])
    }

    /// Handle the Deposit command.
    ///
    /// BUSINESS RULES:
    ///   - Account must exist
    ///   - Account must be open
    ///   - Deposit amount must be > 0
    ///
    /// PRODUCES: MoneyDeposited event
    async fn handle_deposit(
        &self,
        account_id: String,
        amount: i64,
    ) -> Result<Vec<AccountEvent>, AccountError> {
        // Validate: deposit amount must be positive
        if amount <= 0 {
            return Err(AccountError::InvalidAmount(amount));
        }

        // Load the aggregate to check business rules
        let account = self
            .event_store
            .load_aggregate(&account_id)
            .await?
            .ok_or_else(|| AccountError::AccountNotFound(account_id.clone()))?;

        // Validate: account must be open
        if !account.is_open {
            return Err(AccountError::AccountClosed(account_id.clone()));
        }

        let deposited_at = chrono::Utc::now().to_rfc3339();

        // Create the event
        let event = AccountEvent::MoneyDeposited {
            account_id: account_id.clone(),
            amount,
            deposited_at,
        };

        // Append to event store with optimistic concurrency
        let stored_events = self
            .event_store
            .append_events(&account_id, account.version, &[event.clone()])
            .await?;

        // Update projections
        self.projection_store
            .handle_events(&stored_events)
            .await?;

        tracing::info!(
            account_id = %account_id,
            amount = amount,
            new_balance = account.balance + amount,
            "Deposit processed"
        );

        Ok(vec![event])
    }

    /// Handle the Withdraw command.
    ///
    /// BUSINESS RULES:
    ///   - Account must exist
    ///   - Account must be open
    ///   - Withdrawal amount must be > 0
    ///   - Sufficient funds must be available (balance >= amount)
    ///
    /// PRODUCES: MoneyWithdrawn event
    async fn handle_withdraw(
        &self,
        account_id: String,
        amount: i64,
    ) -> Result<Vec<AccountEvent>, AccountError> {
        // Validate: withdrawal amount must be positive
        if amount <= 0 {
            return Err(AccountError::InvalidAmount(amount));
        }

        // Load the aggregate to check business rules
        let account = self
            .event_store
            .load_aggregate(&account_id)
            .await?
            .ok_or_else(|| AccountError::AccountNotFound(account_id.clone()))?;

        // Validate: account must be open
        if !account.is_open {
            return Err(AccountError::AccountClosed(account_id.clone()));
        }

        // Validate: sufficient funds
        if account.balance < amount {
            return Err(AccountError::InsufficientFunds {
                balance: account.balance,
                requested: amount,
            });
        }

        let withdrawn_at = chrono::Utc::now().to_rfc3339();

        // Create the event
        let event = AccountEvent::MoneyWithdrawn {
            account_id: account_id.clone(),
            amount,
            withdrawn_at,
        };

        // Append to event store with optimistic concurrency
        let stored_events = self
            .event_store
            .append_events(&account_id, account.version, &[event.clone()])
            .await?;

        // Update projections
        self.projection_store
            .handle_events(&stored_events)
            .await?;

        tracing::info!(
            account_id = %account_id,
            amount = amount,
            new_balance = account.balance - amount,
            "Withdrawal processed"
        );

        Ok(vec![event])
    }

    /// Get the current state of an account (rebuilt from events).
    ///
    /// This is the QUERY side of CQRS. It reads from the event store
    /// (via snapshot + replay) and returns the current aggregate state.
    pub async fn get_account(&self, account_id: &str) -> Result<Option<Account>, AccountError> {
        self.event_store.load_aggregate(account_id).await
    }

    /// Get the transaction history for an account (from projections).
    ///
    /// This is an alternative read model — optimized for displaying
    /// a list of transactions rather than computing the current balance.
    pub async fn get_transaction_history(
        &self,
        account_id: &str,
    ) -> Result<Vec<crate::projection::Transaction>, AccountError> {
        self.projection_store
            .get_transactions(account_id)
            .await
            .map_err(|e| AccountError::Database(e.to_string()))
    }

    /// Get all events for an account (full audit trail).
    pub async fn get_event_history(
        &self,
        account_id: &str,
    ) -> Result<Vec<crate::event_store::StoredEvent>, AccountError> {
        self.event_store.read_events(account_id).await
    }
}
