// =============================================================================
// domain.rs — Core Business Entities
// =============================================================================
//
// This is the innermost layer of Clean Architecture. It contains:
//   - TaskStatus: the lifecycle states a task can be in
//   - Task: the core domain entity
//
// CLEAN ARCHITECTURE RULE: Domain layer has ZERO external dependencies.
//   The only exception here is serde, which is a pragmatic choice for
//   serialization. In a stricter interpretation, you'd define your own
//   serialization traits. But serde is so ubiquitous in Rust that it's
//   considered acceptable.
//
// WHY SEPARATE DOMAIN FROM APPLICATION?
//   - Domain types don't change when infrastructure changes (e.g., SQLite -> Postgres)
//   - Domain logic can be unit tested without any infrastructure
//   - Domain is the "heart" of the system — it should be the most stable part
// =============================================================================

use serde::{Deserialize, Serialize};

// =============================================================================
// TaskStatus Enum
// =============================================================================
//
// The lifecycle of a task follows a simple state machine:
//
//   Pending ──► Processing ──► Done
//
// Pending:   Task has been created but not yet picked up by the worker
// Processing: Worker is actively processing the task
// Done:      Processing completed successfully
//
// WHY NOT INCLUDE A "Failed" STATE?
//   In this demo, tasks always succeed (the retry logic eventually completes).
//   In production, you'd add Failed and possibly a dead-letter state.
//   The state machine would be:
//     Pending ──► Processing ──► Done
//                      │
//                      ▼ (after N retries)
//                    Failed
//
// WHY DERIVE THESE TRAITS?
//   - Clone: So we can pass tasks around without ownership issues
//   - Debug: For logging and error messages
//   - PartialEq: For testing assertions
//   - Serialize/Deserialize: For JSON logging and potential message queue use
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum TaskStatus {
    Pending,
    Processing,
    Done,
}

impl TaskStatus {
    /// Convert the enum to a static string for storage/comparison.
    /// We use &'static str (not String) because the values are fixed at compile time.
    /// This avoids heap allocation for every conversion.
    pub fn as_str(&self) -> &'static str {
        match self {
            TaskStatus::Pending => "Pending",
            TaskStatus::Processing => "Processing",
            TaskStatus::Done => "Done",
        }
    }

    /// Parse a string back into a TaskStatus.
    /// Returns None for unknown strings (graceful degradation).
    /// This is used when reading status from the database (stored as TEXT).
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "Pending" => Some(TaskStatus::Pending),
            "Processing" => Some(TaskStatus::Processing),
            "Done" => Some(TaskStatus::Done),
            _ => None,
        }
    }
}

// =============================================================================
// Task Entity
// =============================================================================
//
// WHY IS THIS CALLED AN "ENTITY" AND NOT JUST A "STRUCT"?
//   In Domain-Driven Design (DDD), an Entity is an object with a unique
//   identity that persists over time. A Task is an entity because:
//   - It has an ID that identifies it uniquely
//   - Its state changes over time (Pending -> Processing -> Done)
//   - Two Tasks with the same description but different IDs are different tasks
//
// CONTRAST WITH VALUE OBJECTS:
//   A Value Object has no identity — two value objects with the same data
//   are considered equal. For example, an Address or Money type.
//   TaskStatus is a value object (two Pending statuses are the same).
//   Task is an entity (two tasks with different IDs are different).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Task {
    /// Unique identifier (UUID v4).
    /// Generated by the server when the task is created.
    pub id: String,

    /// Human-readable description of the task.
    /// Provided by the client in the CreateTask request.
    pub description: String,

    /// Current lifecycle status.
    /// Starts as Pending, transitions through Processing to Done.
    pub status: TaskStatus,
}
