FROM python:3.12-slim

RUN apt-get update && apt-get install -y build-essential git python3-pytest
WORKDIR /src

RUN git clone https://github.com/sunpy/sunpy.git sunpy-git
WORKDIR /src/sunpy-git
RUN git checkout a1a081a

RUN pip install -e ".[tests]"