name: CI

# --------------------------------------------------
# When this workflow runs
# --------------------------------------------------
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# --------------------------------------------------
# Global environment variables
# --------------------------------------------------
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

# --------------------------------------------------
# Jobs
# --------------------------------------------------
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install Rust toolchain
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # 3️⃣ Cache cargo dependencies
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 4️⃣ Check formatting
      - name: Cargo fmt
        run: cargo fmt --all -- --check

      # 5️⃣ Lint with Clippy
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # 6️⃣ Run tests
      - name: Cargo test
        run: cargo test --all-features

      # 7️⃣ Build release (sanity check)
      - name: Cargo build (release)
        run: cargo build --release
