//// RUST DATABASE INTEGRATION - DIESEL AND SQLX
/// Comprehensive guide to database access in Rust
/// Covers both major ORMs: Diesel (type-safe) and SQLx (async, compile-time checked)

// ============================================================================
// 1. DIESEL - TYPE-SAFE ORM
// ============================================================================

/// Diesel is a safe, extensible ORM and Query Builder
/// Key features:
/// - Compile-time query validation
/// - Type-safe query builder
/// - Supports PostgreSQL, MySQL, SQLite
/// - Migration system
/// - Connection pooling

/*
INSTALLATION:
cargo add diesel --features postgres
cargo install diesel_cli --no-default-features --features postgres

SETUP:
1. Set DATABASE_URL environment variable
   export DATABASE_URL=postgres://user:pass@localhost/mydb

2. Initialize Diesel
   diesel setup
   
3. Create migration
   diesel migration generate create_users
   
4. Write migration SQL (migrations/xxx_create_users/up.sql)
   CREATE TABLE users (
     id SERIAL PRIMARY KEY,
     username VARCHAR NOT NULL UNIQUE,
     email VARCHAR NOT NULL,
     created_at TIMESTAMP NOT NULL DEFAULT NOW()
   );
   
5. Run migration
   diesel migration run
*/

// ============================================================================
// 2. DIESEL SCHEMA AND MODELS
// ============================================================================

/// Schema (generated by Diesel CLI in src/schema.rs)
/*
// @generated automatically by Diesel CLI.

diesel::table! {
    users (id) {
        id -> Int4,
        username -> Varchar,
        email -> Varchar,
        created_at -> Timestamp,
    }
}

diesel::table! {
    posts (id) {
        id -> Int4,
        user_id -> Int4,
        title -> Varchar,
        body -> Text,
        published -> Bool,
        created_at -> Timestamp,
    }
}

diesel::joinable!(posts -> users (user_id));
diesel::allow_tables_to_appear_in_same_query!(users, posts);
*/

/// Models
/*
use diesel::prelude::*;
use chrono::NaiveDateTime;
use serde::{Serialize, Deserialize};

// Queryable model (for reading from DB)
#[derive(Queryable, Selectable, Debug, Serialize)]
#[diesel(table_name = users)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub email: String,
    pub created_at: NaiveDateTime,
}

// Insertable model (for inserting into DB)
#[derive(Insertable, Deserialize)]
#[diesel(table_name = users)]
pub struct NewUser {
    pub username: String,
    pub email: String,
}

// AsChangeset for updates
#[derive(AsChangeset, Deserialize)]
#[diesel(table_name = users)]
pub struct UpdateUser {
    pub username: Option<String>,
    pub email: Option<String>,
}
*/


// ============================================================================
// 3. DIESEL CRUD OPERATIONS
// ============================================================================

/*
use diesel::prelude::*;
use diesel::pg::PgConnection;

// Establish connection
fn establish_connection() -> PgConnection {
    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");
    
    PgConnection::establish(&database_url)
        .expect("Error connecting to database")
}

// CREATE
fn create_user(conn: &mut PgConnection, username: &str, email: &str) -> User {
    use crate::schema::users;
    
    let new_user = NewUser {
        username: username.to_string(),
        email: email.to_string(),
    };
    
    diesel::insert_into(users::table)
        .values(&new_user)
        .returning(User::as_returning())
        .get_result(conn)
        .expect("Error saving user")
}

// READ - Single
fn get_user(conn: &mut PgConnection, user_id: i32) -> Option<User> {
    use crate::schema::users::dsl::*;
    
    users
        .find(user_id)
        .select(User::as_select())
        .first(conn)
        .optional()
        .expect("Error loading user")
}

// READ - Multiple
fn list_users(conn: &mut PgConnection, limit: i64) -> Vec<User> {
    use crate::schema::users::dsl::*;
    
    users
        .limit(limit)
        .select(User::as_select())
        .load(conn)
        .expect("Error loading users")
}

// READ - With filter
fn find_user_by_username(conn: &mut PgConnection, user_name: &str) -> Option<User> {
    use crate::schema::users::dsl::*;
    
    users
        .filter(username.eq(user_name))
        .select(User::as_select())
        .first(conn)
        .optional()
        .expect("Error loading user")
}

// UPDATE
fn update_user(conn: &mut PgConnection, user_id: i32, changes: UpdateUser) -> User {
    use crate::schema::users::dsl::*;
    
    diesel::update(users.find(user_id))
        .set(&changes)
        .returning(User::as_returning())
        .get_result(conn)
        .expect("Error updating user")
}

// DELETE
fn delete_user(conn: &mut PgConnection, user_id: i32) -> usize {
    use crate::schema::users::dsl::*;
    
    diesel::delete(users.find(user_id))
        .execute(conn)
        .expect("Error deleting user")
}
*/


// ============================================================================
// 4. DIESEL ADVANCED QUERIES
// ============================================================================

/*
// JOIN queries
fn get_users_with_posts(conn: &mut PgConnection) -> Vec<(User, Post)> {
    use crate::schema::{users, posts};
    
    users::table
        .inner_join(posts::table)
        .select((User::as_select(), Post::as_select()))
        .load(conn)
        .expect("Error loading users with posts")
}

// Aggregation
fn count_users(conn: &mut PgConnection) -> i64 {
    use crate::schema::users::dsl::*;
    use diesel::dsl::count;
    
    users
        .select(count(id))
        .first(conn)
        .expect("Error counting users")
}

// Complex filtering
fn search_users(conn: &mut PgConnection, query: &str) -> Vec<User> {
    use crate::schema::users::dsl::*;
    
    users
        .filter(
            username.like(format!("%{}%", query))
            .or(email.like(format!("%{}%", query)))
        )
        .select(User::as_select())
        .load(conn)
        .expect("Error searching users")
}

// Transactions
fn transfer_money(
    conn: &mut PgConnection,
    from_id: i32,
    to_id: i32,
    amount: i32
) -> Result<(), diesel::result::Error> {
    conn.transaction(|conn| {
        // Deduct from sender
        diesel::update(accounts::table.find(from_id))
            .set(balance.eq(balance - amount))
            .execute(conn)?;
        
        // Add to receiver
        diesel::update(accounts::table.find(to_id))
            .set(balance.eq(balance + amount))
            .execute(conn)?;
        
        Ok(())
    })
}
*/


// ============================================================================
// 5. DIESEL CONNECTION POOLING
// ============================================================================

/*
use diesel::r2d2::{self, ConnectionManager};
use diesel::PgConnection;

pub type DbPool = r2d2::Pool<ConnectionManager<PgConnection>>;

pub fn create_pool() -> DbPool {
    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");
    
    let manager = ConnectionManager::<PgConnection>::new(database_url);
    
    r2d2::Pool::builder()
        .max_size(10)
        .min_idle(Some(2))
        .connection_timeout(std::time::Duration::from_secs(5))
        .build(manager)
        .expect("Failed to create pool")
}

// Usage with web framework
use actix_web::{web, App, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let pool = create_pool();
    
    HttpServer::new(move || {
        App::new()
            .app_data(web::Data::new(pool.clone()))
            .route("/users", web::get().to(get_users))
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}

async fn get_users(pool: web::Data<DbPool>) -> Result<web::Json<Vec<User>>, actix_web::Error> {
    let mut conn = pool.get().expect("couldn't get db connection");
    
    let users = web::block(move || {
        list_users(&mut conn, 10)
    })
    .await
    .map_err(|e| actix_web::error::ErrorInternalServerError(e))?;
    
    Ok(web::Json(users))
}
*/


// ============================================================================
// 6. SQLX - ASYNC DATABASE ACCESS
// ============================================================================

/// SQLx is an async, pure Rust SQL library
/// Key features:
/// - Compile-time query validation (with macros)
/// - Async/await support
/// - No ORM overhead
/// - Supports PostgreSQL, MySQL, SQLite
/// - Connection pooling built-in

/*
INSTALLATION:
cargo add sqlx --features postgres,runtime-tokio-rustls,macros

SETUP:
1. Set DATABASE_URL
   export DATABASE_URL=postgres://user:pass@localhost/mydb

2. Create database
   sqlx database create

3. Run migrations
   sqlx migrate run
*/


// ============================================================================
// 7. SQLX CRUD OPERATIONS
// ============================================================================

/*
use sqlx::{PgPool, FromRow, postgres::PgPoolOptions};
use serde::{Serialize, Deserialize};

#[derive(Debug, FromRow, Serialize)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub email: String,
    pub created_at: chrono::NaiveDateTime,
}

#[derive(Debug, Deserialize)]
pub struct CreateUser {
    pub username: String,
    pub email: String,
}

// CREATE - with query! macro (compile-time checked)
pub async fn create_user(pool: &PgPool, user: CreateUser) -> Result<User, sqlx::Error> {
    let user = sqlx::query_as!(
        User,
        r#"
        INSERT INTO users (username, email)
        VALUES ($1, $2)
        RETURNING id, username, email, created_at
        "#,
        user.username,
        user.email
    )
    .fetch_one(pool)
    .await?;
    
    Ok(user)
}

// READ - Single
pub async fn get_user(pool: &PgPool, user_id: i32) -> Result<Option<User>, sqlx::Error> {
    let user = sqlx::query_as!(
        User,
        r#"
        SELECT id, username, email, created_at
        FROM users
        WHERE id = $1
        "#,
        user_id
    )
    .fetch_optional(pool)
    .await?;
    
    Ok(user)
}

// READ - Multiple
pub async fn list_users(pool: &PgPool, limit: i64) -> Result<Vec<User>, sqlx::Error> {
    let users = sqlx::query_as!(
        User,
        r#"
        SELECT id, username, email, created_at
        FROM users
        ORDER BY created_at DESC
        LIMIT $1
        "#,
        limit
    )
    .fetch_all(pool)
    .await?;
    
    Ok(users)
}

// UPDATE
pub async fn update_user_email(
    pool: &PgPool,
    user_id: i32,
    new_email: &str
) -> Result<User, sqlx::Error> {
    let user = sqlx::query_as!(
        User,
        r#"
        UPDATE users
        SET email = $2
        WHERE id = $1
        RETURNING id, username, email, created_at
        "#,
        user_id,
        new_email
    )
    .fetch_one(pool)
    .await?;
    
    Ok(user)
}

// DELETE
pub async fn delete_user(pool: &PgPool, user_id: i32) -> Result<u64, sqlx::Error> {
    let result = sqlx::query!(
        r#"
        DELETE FROM users
        WHERE id = $1
        "#,
        user_id
    )
    .execute(pool)
    .await?;
    
    Ok(result.rows_affected())
}
*/


// ============================================================================
// 8. SQLX CONNECTION POOL
// ============================================================================

/*
use sqlx::postgres::PgPoolOptions;
use std::time::Duration;

pub async fn create_pool() -> Result<PgPool, sqlx::Error> {
    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");
    
    PgPoolOptions::new()
        .max_connections(10)
        .min_connections(2)
        .acquire_timeout(Duration::from_secs(5))
        .idle_timeout(Duration::from_secs(600))
        .max_lifetime(Duration::from_secs(1800))
        .connect(&database_url)
        .await
}

// Usage with Axum
use axum::{
    Router,
    routing::get,
    extract::{State, Path},
    Json,
};

#[derive(Clone)]
struct AppState {
    pool: PgPool,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let pool = create_pool().await?;
    
    let state = AppState { pool };
    
    let app = Router::new()
        .route("/users", get(get_users_handler))
        .route("/users/:id", get(get_user_handler))
        .with_state(state);
    
    let listener = tokio::net::TcpListener::bind("127.0.0.1:3000").await?;
    axum::serve(listener, app).await?;
    
    Ok(())
}

async fn get_users_handler(
    State(state): State<AppState>
) -> Result<Json<Vec<User>>, (StatusCode, String)> {
    let users = list_users(&state.pool, 10)
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    
    Ok(Json(users))
}

async fn get_user_handler(
    State(state): State<AppState>,
    Path(user_id): Path<i32>
) -> Result<Json<User>, (StatusCode, String)> {
    let user = get_user(&state.pool, user_id)
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?
        .ok_or((StatusCode::NOT_FOUND, "User not found".to_string()))?;
    
    Ok(Json(user))
}
*/


// ============================================================================
// 9. SQLX TRANSACTIONS
// ============================================================================

/*
use sqlx::{PgPool, Postgres, Transaction};

pub async fn transfer_money(
    pool: &PgPool,
    from_id: i32,
    to_id: i32,
    amount: i32
) -> Result<(), sqlx::Error> {
    // Start transaction
    let mut tx: Transaction<Postgres> = pool.begin().await?;
    
    // Deduct from sender
    sqlx::query!(
        r#"
        UPDATE accounts
        SET balance = balance - $2
        WHERE id = $1 AND balance >= $2
        "#,
        from_id,
        amount
    )
    .execute(&mut *tx)
    .await?;
    
    // Add to receiver
    sqlx::query!(
        r#"
        UPDATE accounts
        SET balance = balance + $2
        WHERE id = $1
        "#,
        to_id,
        amount
    )
    .execute(&mut *tx)
    .await?;
    
    // Commit transaction
    tx.commit().await?;
    
    Ok(())
}
*/


// ============================================================================
// 10. COMPARISON: DIESEL VS SQLX
// ============================================================================

/// DIESEL:
/// ✓ Type-safe query builder
/// ✓ Compile-time query validation
/// ✓ Great IDE support
/// ✓ Strong type system integration
/// ✓ Migration system
/// ✗ Synchronous (blocking)
/// ✗ Steeper learning curve
/// 
/// Use when:
/// - You want maximum type safety
/// - Complex query building
/// - Strong ORM patterns
/// - Blocking I/O is acceptable

/// SQLX:
/// ✓ Async/await support
/// ✓ Compile-time query checking (with macros)
/// ✓ Simpler mental model
/// ✓ Direct SQL control
/// ✓ Better for async applications
/// ✗ Less abstraction
/// ✗ More manual query writing
/// 
/// Use when:
/// - You need async database access
/// - Building async web services
/// - Want direct SQL control
/// - Performance is critical


// ============================================================================
// 11. BEST PRACTICES
// ============================================================================

/// DATABASE BEST PRACTICES:
/// 
/// 1. USE CONNECTION POOLING
///    - Reuse connections
///    - Configure pool size appropriately
///    - Set timeouts
/// 
/// 2. HANDLE ERRORS PROPERLY
///    - Don't unwrap in production
///    - Use proper error types
///    - Log database errors
/// 
/// 3. USE TRANSACTIONS
///    - For multiple related operations
///    - Ensure atomicity
///    - Keep transactions short
/// 
/// 4. AVOID N+1 QUERIES
///    - Use JOINs or eager loading
///    - Batch operations
///    - Profile query performance
/// 
/// 5. INDEX APPROPRIATELY
///    - Index frequently queried columns
///    - Monitor slow queries
///    - Don't over-index
/// 
/// 6. USE PREPARED STATEMENTS
///    - Both Diesel and SQLx do this
///    - Prevents SQL injection
///    - Better performance
/// 
/// 7. MIGRATIONS
///    - Version control your schema
///    - Test migrations
///    - Reversible migrations
/// 
/// 8. SECURITY
///    - Never concatenate user input into SQL
///    - Use parameterized queries
///    - Validate input
///    - Limit database permissions
/// 
/// 9. MONITORING
///    - Query performance
///    - Connection pool utilization
///    - Error rates
///    - Database size
/// 
/// 10. TESTING
///     - Use test database
///     - Clean up after tests
///     - Test transactions
///     - Test error cases


fn main() {
    println!("=== RUST DATABASE INTEGRATION ===\n");
    println!("This file demonstrates Diesel and SQLx patterns.");
    println!("See comments for complete examples.\n");
    
    println!("DIESEL:");
    println!("  ✓ Type-safe ORM");
    println!("  ✓ Query builder");
    println!("  ✓ Migration system");
    println!("  ✗ Synchronous (blocking)");
    
    println!("\nSQLX:");
    println!("  ✓ Async database access");
    println!("  ✓ Compile-time query checking");
    println!("  ✓ Direct SQL control");
    println!("  ✓ Built-in pooling");
    
    println!("\nCHOOSE DIESEL IF:");
    println!("  • You want maximum type safety");
    println!("  • Complex query building");
    println!("  • Blocking I/O acceptable");
    
    println!("\nCHOOSE SQLX IF:");
    println!("  • Building async web services");
    println!("  • Need async/await support");
    println!("  • Want direct SQL control");
    
    println!("\n=== Complete ===");
}

/// DEPENDENCIES:
/// 
/// For Diesel:
/// ```toml
/// [dependencies]
/// diesel = { version = "2", features = ["postgres", "r2d2", "chrono"] }
/// chrono = "0.4"
/// serde = { version = "1", features = ["derive"] }
/// 
/// [dev-dependencies]
/// diesel_migrations = "2"
/// ```
/// 
/// For SQLx:
/// ```toml
/// [dependencies]
/// sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "macros", "chrono"] }
/// tokio = { version = "1", features = ["full"] }
/// chrono = "0.4"
/// serde = { version = "1", features = ["derive"] }
/// ```
